#!/usr/bin/env python3
"""PreToolUse hook: block newly-added top-of-file comments.

Banner/preamble comments at the top of a source file ("this file does X",
port notes, leftover narration) add noise and drift out of sync. This hook
blocks an edit that *introduces* a leading comment into a file that didn't
already open with one. Files already opening with a comment are grandfathered
— the hook only guards currently-clean files.

Exempt leading lines (skipped before the check): shebangs, license/copyright
headers, lint/type pragmas, generated-file markers, and Python module
docstrings (a real language construct, not a comment). See
`.claude/rules/no-top-of-file-comments.md`.

Exit codes:
  0 = allow the edit
  2 = block the edit (stderr message surfaces back to Claude)
"""

import json
import subprocess
import sys
from pathlib import Path

_PY_EXT = (".py",)
_C_STYLE_EXT = (".ts", ".tsx", ".js", ".jsx", ".mjs", ".cjs", ".dart")
_GUARDED_EXT = _PY_EXT + _C_STYLE_EXT

# Substrings that make a leading comment legitimate (matched case-insensitively).
_EXEMPT_COMMENT_SUBSTRINGS = (
    "copyright",
    "license",
    "spdx-license-identifier",
    "@license",
    "@generated",
    "auto-generated",
    "autogenerated",
    "do not edit",
    "code generated by",
    "eslint-disable",
    "@ts-nocheck",
    "@ts-expect-error",
    "prettier-ignore",
    "noqa",
    "type: ignore",
    "ruff:",
    "mypy:",
    "pylint:",
)


def main() -> int:
    target = _target_of_edit()
    if target is None:
        return 0
    file_path, new_content = target

    # Only guard files that are currently clean: if HEAD already opens with a
    # top-of-file comment, this file is grandfathered — don't fight edits to it.
    head_content = _read_head_content(file_path) or ""
    if _opens_with_comment(head_content, file_path):
        return 0
    if not _opens_with_comment(new_content, file_path):
        return 0

    sys.stderr.write(
        f"❌ top-of-file-comment hook blocked edit to {file_path}:\n"
        "  - adds a banner/preamble comment at the top of the file.\n"
        "    remove it — put purpose in names and structure, not a preamble.\n"
        "    (shebangs, license headers, lint/type pragmas, generated-file\n"
        "    markers, and Python module docstrings are exempt.)\n"
        "    see `.claude/rules/no-top-of-file-comments.md`.\n"
    )
    return 2


def _target_of_edit() -> tuple[str, str] | None:
    """Parse stdin; return (file_path, post-edit content) for a guarded edit, else None."""
    try:
        payload = json.load(sys.stdin)
    except json.JSONDecodeError:
        return None
    if payload.get("tool_name", "") not in ("Edit", "Write", "MultiEdit"):
        return None
    tool_input = payload.get("tool_input", {}) or {}
    file_path = tool_input.get("file_path", "")
    if not file_path or not file_path.endswith(_GUARDED_EXT):
        return None
    new_content = _resolve_post_edit_content(payload["tool_name"], tool_input, file_path)
    if new_content is None:
        return None
    return file_path, new_content


def _opens_with_comment(content: str, file_path: str) -> bool:
    """True if the file's first meaningful line is a disallowed comment."""
    lines = content.splitlines()
    idx = _skip_exempt_leading(lines, file_path)
    if idx >= len(lines):
        return False
    stripped = lines[idx].lstrip()
    if not stripped:
        return False
    if file_path.endswith(_PY_EXT):
        # A module docstring is a language construct, not a comment — allow it.
        if stripped.startswith(('"""', "'''", 'r"""', "r'''")):
            return False
        return stripped.startswith("#")
    return stripped.startswith("//") or stripped.startswith("/*")


def _skip_exempt_leading(lines: list[str], file_path: str) -> int:
    """Return the index of the first line that isn't blank or an exempt leader."""
    idx = 0
    while idx < len(lines):
        stripped = lines[idx].strip()
        if not stripped:
            idx += 1
            continue
        if idx == 0 and stripped.startswith("#!"):
            idx += 1
            continue
        if _is_comment_line(stripped, file_path) and _is_exempt_comment(stripped):
            idx += 1
            continue
        break
    return idx


def _is_comment_line(stripped: str, file_path: str) -> bool:
    if file_path.endswith(_PY_EXT):
        return stripped.startswith("#")
    return stripped.startswith("//") or stripped.startswith("/*")


def _is_exempt_comment(stripped: str) -> bool:
    lowered = stripped.lower()
    return any(sub in lowered for sub in _EXEMPT_COMMENT_SUBSTRINGS)


def _resolve_post_edit_content(tool_name: str, tool_input: dict, file_path: str) -> str | None:
    """Return the file content as it would be after the tool applies."""
    if tool_name == "Write":
        return tool_input.get("content", "")

    try:
        current = Path(file_path).read_text()
    except (OSError, UnicodeDecodeError):
        return None

    if tool_name == "Edit":
        return _apply_edit(
            current,
            tool_input.get("old_string", ""),
            tool_input.get("new_string", ""),
            tool_input.get("replace_all", False),
        )

    if tool_name == "MultiEdit":
        result = current
        for edit in tool_input.get("edits", []) or []:
            result = _apply_edit(
                result,
                edit.get("old_string", ""),
                edit.get("new_string", ""),
                edit.get("replace_all", False),
            )
        return result

    return None


def _apply_edit(current: str, old: str, new: str, replace_all: bool) -> str:
    if not old:
        return current
    if replace_all:
        return current.replace(old, new)
    return current.replace(old, new, 1)


def _read_head_content(file_path: str) -> str | None:
    """Return the file's HEAD content from git, or None if not tracked."""
    try:
        result = subprocess.run(
            ["git", "show", f"HEAD:./{_relpath(file_path)}"],
            capture_output=True,
            text=True,
            cwd=_repo_root(file_path),
            timeout=5,
        )
    except (subprocess.SubprocessError, OSError):
        return None
    if result.returncode != 0:
        return None
    return result.stdout


def _repo_root(file_path: str) -> str:
    p = Path(file_path).resolve()
    while p != p.parent:
        if (p / ".git").exists():
            return str(p)
        p = p.parent
    return str(Path(file_path).parent)


def _relpath(file_path: str) -> str:
    root = Path(_repo_root(file_path))
    try:
        return str(Path(file_path).resolve().relative_to(root))
    except ValueError:
        return file_path


if __name__ == "__main__":
    sys.exit(main())
