# Generated by Django 6.0.3 on 2026-04-08 13:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[("event_invite", "Event Invite"), ("join_request", "Join Request")],
                default="event_invite",
                max_length=32,
            ),
        ),
    ]
