# Generated by Django 6.0.3 on 2026-04-08 22:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0002_alter_notification_notification_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("event_invite", "Event Invite"),
                    ("join_request", "Join Request"),
                    ("cohost_added", "Co-host Added"),
                ],
                default="event_invite",
                max_length=32,
            ),
        ),
    ]
