# Generated by Django 6.0.3 on 2026-04-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0005_notification_related_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("event_invite", "Event Invite"),
                    ("event_cancelled", "Event Cancelled"),
                    ("join_request", "Join Request"),
                    ("cohost_added", "Co-host Added"),
                    ("magic_link_request", "Magic Link Request"),
                ],
                default="event_invite",
                max_length=32,
            ),
        ),
    ]
