# Generated by Django 6.0.3 on 2026-07-14 18:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0013_alter_notification_notification_type'),
        ('notifications', '0013_sseticket'),
    ]

    operations = [
    ]
