# Generated by Django 6.0.3 on 2026-07-22 22:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("notifications", "0014_merge_20260714_1825"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="notification_type",
            field=models.CharField(
                choices=[
                    ("event_invite", "Event Invite"),
                    ("event_cancelled", "Event Cancelled"),
                    ("join_request", "Join Request"),
                    ("cohost_added", "Co-host Added"),
                    ("cohost_invite", "Co-host Invite"),
                    ("cohost_invite_accepted", "Co-host Invite Accepted"),
                    ("cohost_invite_declined", "Co-host Invite Declined"),
                    ("cohost_removed", "Co-host Removed"),
                    ("magic_link_request", "Magic Link Request"),
                    ("waitlist_promoted", "Waitlist Promoted"),
                    ("event_flagged", "Event Flagged"),
                    ("comment_reply", "Comment Reply"),
                    ("event_comment", "Event Comment"),
                    ("rsvp_declined_note", "RSVP Declined Note"),
                    ("checkin_nudge", "Check-in Nudge"),
                ],
                default="event_invite",
                max_length=32,
            ),
        ),
    ]
