"""Tests for event tags — the curated, admin-managed tag set and its
assignment to events via create/update."""

import pytest
from community.models import Event, EventTag
from django.db import connection
from django.test.utils import CaptureQueriesContext
from users.models import User

from tests.conftest import future_iso


@pytest.fixture
def member_headers(db):
    from ninja_jwt.tokens import RefreshToken

    member = User.objects.create_user(
        phone_number="+14155550111",
        password="memberpass123",
        display_name="Tag Member",
    )
    return {"HTTP_AUTHORIZATION": f"Bearer {RefreshToken.for_user(member).access_token}"}  # type: ignore


@pytest.fixture
def tags(db):
    walk = EventTag.objects.create(name="walk")
    meetup = EventTag.objects.create(name="restaurant meetup")
    return walk, meetup


@pytest.mark.django_db
class TestEventTagModel:
    def test_slug_autogenerated_from_name(self):
        tag = EventTag.objects.create(name="restaurant meetup")
        assert tag.slug == "restaurant-meetup"

    def test_explicit_slug_preserved(self):
        tag = EventTag.objects.create(name="Walk", slug="custom-walk")
        assert tag.slug == "custom-walk"


@pytest.mark.django_db
class TestListEventTags:
    def test_list_event_tags_public(self, api_client, tags):
        response = api_client.get("/api/community/event-tags/")
        assert response.status_code == 200
        names = [t["name"] for t in response.json()]
        # ordered by name
        assert names == ["restaurant meetup", "walk"]

    def test_list_event_tags_shape(self, api_client, tags):
        response = api_client.get("/api/community/event-tags/")
        first = response.json()[0]
        assert set(first.keys()) == {"id", "name", "slug"}


@pytest.mark.django_db
class TestAssignTagsOnCreate:
    def test_create_event_with_tags(self, api_client, member_headers, tags):
        walk, meetup = tags
        response = api_client.post(
            "/api/community/events/",
            {
                "title": "Tagged Event",
                "start_datetime": future_iso(days=14),
                "end_datetime": future_iso(days=14, hours=2),
                "tag_ids": [str(walk.id), str(meetup.id)],
            },
            content_type="application/json",
            **member_headers,
        )
        assert response.status_code == 201
        returned = {t["slug"] for t in response.json()["tags"]}
        assert returned == {"walk", "restaurant-meetup"}

    def test_create_event_without_tags_defaults_empty(self, api_client, member_headers):
        response = api_client.post(
            "/api/community/events/",
            {
                "title": "Untagged Event",
                "start_datetime": future_iso(days=14),
                "end_datetime": future_iso(days=14, hours=2),
            },
            content_type="application/json",
            **member_headers,
        )
        assert response.status_code == 201
        assert response.json()["tags"] == []

    def test_create_event_unknown_tag_id_ignored(self, api_client, member_headers, tags):
        walk, _ = tags
        unknown = "00000000-0000-0000-0000-000000000000"
        response = api_client.post(
            "/api/community/events/",
            {
                "title": "Partly Tagged",
                "start_datetime": future_iso(days=14),
                "end_datetime": future_iso(days=14, hours=2),
                "tag_ids": [str(walk.id), unknown],
            },
            content_type="application/json",
            **member_headers,
        )
        assert response.status_code == 201
        returned = {t["slug"] for t in response.json()["tags"]}
        assert returned == {"walk"}


@pytest.mark.django_db
class TestUpdateTags:
    def _make_event(self, creator: User, *tag_objs: EventTag) -> Event:
        event = Event.objects.create(
            title="Editable Event",
            start_datetime=future_iso(days=7),
            end_datetime=future_iso(days=7, hours=2),
            created_by=creator,
        )
        if tag_objs:
            event.tags.set(tag_objs)
        return event

    def test_patch_replaces_tags(self, api_client, member_headers, tags):
        walk, meetup = tags
        creator = User.objects.get(phone_number="+14155550111")
        event = self._make_event(creator, walk)
        response = api_client.patch(
            f"/api/community/events/{event.id}/",
            {"tag_ids": [str(meetup.id)]},
            content_type="application/json",
            **member_headers,
        )
        assert response.status_code == 200
        returned = {t["slug"] for t in response.json()["tags"]}
        assert returned == {"restaurant-meetup"}

    def test_patch_clears_tags_with_empty_list(self, api_client, member_headers, tags):
        walk, _ = tags
        creator = User.objects.get(phone_number="+14155550111")
        event = self._make_event(creator, walk)
        response = api_client.patch(
            f"/api/community/events/{event.id}/",
            {"tag_ids": []},
            content_type="application/json",
            **member_headers,
        )
        assert response.status_code == 200
        assert response.json()["tags"] == []

    def test_patch_omitting_tag_ids_leaves_tags_untouched(self, api_client, member_headers, tags):
        walk, _ = tags
        creator = User.objects.get(phone_number="+14155550111")
        event = self._make_event(creator, walk)
        response = api_client.patch(
            f"/api/community/events/{event.id}/",
            {"title": "Renamed"},
            content_type="application/json",
            **member_headers,
        )
        assert response.status_code == 200
        returned = {t["slug"] for t in response.json()["tags"]}
        assert returned == {"walk"}


@pytest.mark.django_db
class TestTagsInListEndpoint:
    def test_list_events_includes_tags(self, api_client, tags):
        walk, _ = tags
        event = Event.objects.create(
            title="Listed Event",
            start_datetime=future_iso(days=5),
            end_datetime=future_iso(days=5, hours=2),
        )
        event.tags.set([walk])
        response = api_client.get("/api/community/events/")
        assert response.status_code == 200
        match = next(e for e in response.json() if e["id"] == str(event.id))
        assert [t["slug"] for t in match["tags"]] == ["walk"]

    def test_list_events_tags_do_not_n_plus_one(self, api_client, tags):
        """Tags must be prefetched on the active-list path: the query count must
        not grow with the number of tagged events. A missing `tags` prefetch
        would add one query per event, so doubling the event count would add
        per-event tag queries — this constant-query invariant catches that
        regardless of incidental base-query drift."""
        walk, meetup = tags

        def _make_events(start_index: int, count: int) -> None:
            for i in range(start_index, start_index + count):
                ev = Event.objects.create(
                    title=f"Tagged {i}",
                    start_datetime=future_iso(days=3 + i),
                    end_datetime=future_iso(days=3 + i, hours=2),
                )
                ev.tags.set([walk, meetup])

        _make_events(0, 3)
        with CaptureQueriesContext(connection) as q_small:
            assert api_client.get("/api/community/events/").status_code == 200
        _make_events(3, 3)  # now 6 tagged events
        with CaptureQueriesContext(connection) as q_large:
            response = api_client.get("/api/community/events/")
        assert response.status_code == 200
        # Doubling the events must not change the query count (prefetch holds it
        # constant). Without the prefetch, q_large would exceed q_small.
        assert len(q_large) == len(q_small)
        listed = [e for e in response.json() if e["title"].startswith("Tagged ")]
        assert len(listed) == 6
        assert all(len(e["tags"]) == 2 for e in listed)
