// Shared test fixtures. Factories return a complete, valid object with sensible
// defaults; pass `overrides` to vary the fields a given test cares about.

import type { Event } from '@/models/event';
import {
  AttendanceStatus,
  EventStatus,
  EventType,
  EventVisibility,
  InvitePermission,
  RsvpServerStatus,
} from '@/models/event';

export function makeEvent(overrides: Partial<Event> = {}): Event {
  return {
    id: 'ev1',
    title: 'Test Event',
    description: '',
    startDatetime: new Date(Date.now() + 7 * 24 * 60 * 60 * 1000),
    endDatetime: null,
    location: '',
    latitude: null,
    longitude: null,
    whatsappLink: '',
    partifulLink: '',
    otherLink: '',
    venmoLink: '',
    cashappLink: '',
    zelleInfo: '',
    price: '',
    rsvpEnabled: true,
    allowPlusOnes: false,
    maxAttendees: null,
    attendingCount: 1,
    waitlistedCount: 0,
    invitedCount: 0,
    datetimeTbd: false,
    hasPoll: false,
    datetimePollSlug: null,
    createdById: 'creator',
    createdByName: 'Creator',
    createdByPhotoUrl: '',
    coHostIds: [],
    coHostNames: [],
    coHostPhotoUrls: [],
    coHostInviteIds: [],
    guests: [
      {
        userId: 'a',
        name: 'alice',
        status: RsvpServerStatus.Attending,
        phone: '+15551112222',
        photoUrl: '',
        hasPlusOne: false,
        attendance: AttendanceStatus.Unknown,
      },
      {
        userId: 'b',
        name: 'bob',
        status: RsvpServerStatus.CantGo,
        phone: '+15553334444',
        photoUrl: '',
        hasPlusOne: false,
        attendance: AttendanceStatus.Unknown,
      },
    ],
    myRsvp: null,
    surveySlugs: [],
    invitedUserIds: [],
    invitedUserNames: [],
    invitedUserPhotoUrls: [],
    invitePermission: InvitePermission.AllMembers,
    pendingCohostInvites: [],
    myPendingCohostInviteId: null,
    eventType: EventType.Community,
    visibility: EventVisibility.Public,
    photoUrl: '',
    photoUpdatedAt: null,
    tags: [],
    isPast: false,
    status: EventStatus.Active,
    ...overrides,
  };
}
