# Generated by Django 5.2.12 on 2026-03-25 23:13

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0004_event_partiful_link_event_rsvp_enabled_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="co_hosts",
            field=models.ManyToManyField(
                blank=True, related_name="co_hosted_events", to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
