# Generated by Django 5.2.12 on 2026-03-26 02:19

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0008_alter_joinrequest_phone_number"),
        ("community", "0008_communityguidelines"),
    ]

    operations = []
