# Generated by Django 5.2.12 on 2026-03-26 03:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0010_homepage"),
    ]

    operations = [
        migrations.AddField(
            model_name="homepage",
            name="join_content",
            field=models.TextField(default=""),
        ),
    ]
