# Generated by Django 5.2.12 on 2026-03-31 03:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0022_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="photo",
            field=models.ImageField(blank=True, upload_to="event_photos/"),
        ),
    ]
