# Generated by Django 5.2.12 on 2026-04-01 20:02

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0027_event_latitude_event_longitude"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="datetime_tbd",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="survey",
            name="one_response_per_user",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="surveyquestion",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("textarea", "Text area"),
                    ("select", "Single select"),
                    ("multiselect", "Multi select"),
                    ("dropdown", "Dropdown"),
                    ("number", "Number"),
                    ("yes_no", "Yes / No"),
                    ("rating", "Rating"),
                    ("datetime_poll", "Datetime poll"),
                ],
                default="text",
                max_length=20,
            ),
        ),
        migrations.CreateModel(
            name="DatetimePollResult",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("winning_datetime", models.DateTimeField()),
                ("finalized_at", models.DateTimeField(auto_now_add=True)),
                (
                    "finalized_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="finalized_polls",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "survey",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="poll_result",
                        to="community.survey",
                    ),
                ),
            ],
        ),
    ]
