# Generated by Django 5.2.12 on 2026-04-02 14:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0031_alter_polloption_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="editablepage",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members_only", "Members only"),
                    ("invite_only", "Invite only"),
                ],
                default="public",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="visibility",
            field=models.CharField(
                choices=[
                    ("public", "Public"),
                    ("members_only", "Members only"),
                    ("invite_only", "Invite only"),
                ],
                default="public",
                max_length=20,
            ),
        ),
    ]
