# Generated by Django 6.0.3 on 2026-04-03 12:58

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0032_alter_editablepage_visibility_alter_event_visibility"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="eventrsvp",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="polloption",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="pollvote",
            unique_together=set(),
        ),
        migrations.AddConstraint(
            model_name="eventrsvp",
            constraint=models.UniqueConstraint(fields=("event", "user"), name="unique_event_rsvp"),
        ),
        migrations.AddConstraint(
            model_name="polloption",
            constraint=models.UniqueConstraint(
                fields=("poll", "datetime"), name="unique_poll_option_datetime"
            ),
        ),
        migrations.AddConstraint(
            model_name="pollvote",
            constraint=models.UniqueConstraint(fields=("option", "user"), name="unique_poll_vote"),
        ),
    ]
