# Generated by Django 6.0.3 on 2026-04-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0036_remove_eventrsvp_plus_one_count_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="communityguidelines",
            name="content_html",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="document",
            name="content_html",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="editablepage",
            name="content_html",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="faq",
            name="content_html",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="content_html",
            field=models.TextField(default=""),
        ),
        migrations.AddField(
            model_name="homepage",
            name="join_content_html",
            field=models.TextField(default=""),
        ),
    ]
