# Generated by Django 6.0.3 on 2026-04-10 04:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0038_alter_communityguidelines_content_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("cancelled", "Cancelled")],
                default="active",
                max_length=20,
            ),
        ),
    ]
