# Generated by Django 6.0.3 on 2026-04-16 01:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0040_event_max_attendees_eventrsvp_created_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="deleted_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("cancelled", "Cancelled"), ("deleted", "Deleted")],
                default="active",
                max_length=20,
            ),
        ),
    ]
