# Generated by Django 6.0.3 on 2026-05-23 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0056_alter_eventcommentreaction_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='joinrequest',
            name='email',
            field=models.EmailField(blank=True, default='', max_length=254),
        ),
    ]
