# Generated by Django 6.0.3 on 2026-05-30 03:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0057_joinrequest_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="joinrequest",
            name="guidelines_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
