# Generated by Django 6.0.3 on 2026-06-24 12:54

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0058_joinrequest_guidelines_consent_at"),
    ]

    operations = [
        migrations.DeleteModel(
            name="WhatsAppConfig",
        ),
    ]
