# Generated by Django 6.0.3 on 2026-07-08 22:49

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0061_joinrequest_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrsvp",
            name="note",
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
