# Generated by Django 6.0.3 on 2026-07-09 23:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0062_eventemailblast"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="photo_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
