# Generated by Django 6.0.3 on 2026-07-11 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0063_event_photo_updated_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="event_type",
            field=models.CharField(
                choices=[("official", "Official"), ("community", "Community"), ("club", "Club")],
                default="community",
                max_length=20,
            ),
        ),
    ]
