# Generated by Django 6.0.3 on 2026-07-11 16:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0064_alter_event_event_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="joinrequest",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="joinrequest",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
