# Generated by Django 6.0.3 on 2026-07-13 00:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0066_backfill_joinrequest_names"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="joinrequest",
            name="display_name",
        ),
    ]
