# Generated by Django 6.0.3 on 2026-07-13 16:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0068_rename_welcome_template_name_placeholder"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrsvp",
            name="cancelled_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventrsvp",
            name="checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
