# Generated by Django 6.0.3 on 2026-07-13 23:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0069_eventrsvp_cancelled_at_eventrsvp_checked_in_at"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joinrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("tentative", "Tentatively approved"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
