# Generated by Django 6.0.3 on 2026-07-21 00:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0079_resanitize_content_html"),
    ]

    operations = [
        migrations.AlterField(
            model_name="joinrequest",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
