# Generated by Django 6.0.3 on 2026-07-21 02:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0080_alter_joinrequest_email"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventrsvp",
            name="status",
            field=models.CharField(
                choices=[
                    ("attending", "Attending"),
                    ("maybe", "Maybe"),
                    ("cant_go", "Can't go"),
                    ("waitlisted", "Waitlisted"),
                    ("removed", "Removed"),
                ],
                max_length=20,
            ),
        ),
    ]
