# Generated by Django 6.0.3 on 2026-07-22 15:28

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0082_featureflagstate"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceReminder",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                (
                    "milestone",
                    models.CharField(
                        choices=[
                            ("m10", "10 months"),
                            ("m11", "11 months"),
                            ("m11_5", "11.5 months"),
                            ("m12", "12 months"),
                        ],
                        max_length=10,
                    ),
                ),
                ("anchor_date", models.DateField()),
                ("sent_at", models.DateTimeField(auto_now_add=True)),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="attendance_reminders",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "ordering": ["-sent_at"],
                "constraints": [
                    models.UniqueConstraint(
                        fields=("user", "milestone", "anchor_date"),
                        name="unique_attendance_reminder_per_anchor",
                    )
                ],
            },
        ),
    ]
