# Generated by Django 6.0.3 on 2026-07-22 15:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0083_attendancereminder"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="checkin_nudge_sent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
