# Generated by Django 6.0.3 on 2026-08-01 01:11

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.db.models.functions import Lower


def backfill_multiline_why_questions(apps, schema_editor):
    """Former FE heuristic: labels containing 'why' rendered as a 5-row textarea."""
    JoinFormQuestion = apps.get_model("community", "JoinFormQuestion")
    JoinFormQuestion.objects.annotate(label_l=Lower("label")).filter(
        field_type="text", label_l__contains="why", rows=1
    ).update(rows=5)


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0085_backfill_creator_as_cohost"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrsvp",
            name="answers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="EventRsvpQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=300)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("textarea", "Text area"),
                            ("dropdown", "Dropdown"),
                            ("multiselect", "Multi select"),
                        ],
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                ("required", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvp_questions",
                        to="community.event",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.AddField(
            model_name="joinformquestion",
            name="rows",
            field=models.PositiveSmallIntegerField(default=1),
        ),
        migrations.RunPython(backfill_multiline_why_questions, migrations.RunPython.noop),
    ]
