# Generated by Django 6.0.3 on 2026-08-01 01:11

import uuid

import django.db.models.deletion
from django.db import migrations, models
from django.db.models.functions import Lower


def migrate_join_question_types(apps, schema_editor):
    """Align join wire types with surveys; promote former 'why' text heuristics to textarea."""
    JoinFormQuestion = apps.get_model("community", "JoinFormQuestion")
    JoinFormQuestion.objects.filter(field_type="select").update(field_type="dropdown")
    JoinFormQuestion.objects.annotate(label_l=Lower("label")).filter(
        field_type="text", label_l__contains="why"
    ).update(field_type="textarea")


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0085_backfill_creator_as_cohost"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrsvp",
            name="answers",
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.CreateModel(
            name="EventRsvpQuestion",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("label", models.CharField(max_length=300)),
                (
                    "field_type",
                    models.CharField(
                        choices=[
                            ("textarea", "Text area"),
                            ("dropdown", "Dropdown"),
                            ("multiselect", "Multi select"),
                        ],
                        max_length=20,
                    ),
                ),
                ("options", models.JSONField(blank=True, default=list)),
                ("required", models.BooleanField(default=False)),
                ("display_order", models.PositiveIntegerField(default=0)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rsvp_questions",
                        to="community.event",
                    ),
                ),
            ],
            options={
                "ordering": ["display_order"],
            },
        ),
        migrations.AlterField(
            model_name="joinformquestion",
            name="field_type",
            field=models.CharField(
                choices=[
                    ("text", "Text"),
                    ("textarea", "Text area"),
                    ("dropdown", "Dropdown"),
                ],
                default="text",
                max_length=10,
            ),
        ),
        migrations.RunPython(migrate_join_question_types, migrations.RunPython.noop),
    ]
