# Generated by Django 6.0.3 on 2026-08-01 22:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0086_event_slug"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="eventrsvp",
            options={"ordering": ["created_at", "pk"]},
        ),
    ]
