# Generated by Django 6.0.3 on 2026-08-02 02:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0087_alter_eventrsvp_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrsvp",
            name="paid_confirmed_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="eventrsvp",
            name="paid_revoked_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
