# Generated by Django 6.0.3 on 2026-08-04 02:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0088_eventrsvp_payment_confirmation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="description",
            field=models.TextField(blank=True, max_length=3000),
        ),
    ]
