# Generated by Django 6.0.3 on 2026-08-08 14:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0089_alter_event_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="eventrsvp",
            name="attendance",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("attended", "Attended"),
                    ("no_show", "Didn't go"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
    ]
