# Generated by Django 6.0.3 on 2026-08-09 04:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0090_alter_eventrsvp_attendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrsvp",
            name="plus_one_attendance",
            field=models.CharField(
                choices=[
                    ("unknown", "Unknown"),
                    ("attended", "Attended"),
                    ("didnt_go", "Didn't go"),
                ],
                default="unknown",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="eventrsvp",
            name="plus_one_checked_in_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
