# Generated by Django 6.0.3 on 2026-08-10 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('community', '0093_event_rsvp_questions'),
    ]

    operations = [
        migrations.AddField(
            model_name='eventpoll',
            name='original_end_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='eventpoll',
            name='original_start_datetime',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
