# Generated by Django 6.0.3 on 2026-08-17 13:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0093_event_rsvp_questions"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_partiful_import",
            field=models.BooleanField(default=False),
        ),
    ]
