# Generated by Django 6.0.3 on 2026-09-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0094_event_is_partiful_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="anonymous",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="survey",
            name="confirmation_message",
            field=models.TextField(blank=True, default="", max_length=1000),
        ),
    ]
