# Generated by Django 6.0.3 on 2026-09-13 22:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0094_event_is_partiful_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyquestion",
            name="show_if",
            field=models.JSONField(blank=True, default=None, null=True),
        ),
    ]
