# Generated by Django 6.0.3 on 2026-09-13 22:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0094_event_is_partiful_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="is_legacy",
            field=models.BooleanField(default=False),
        ),
    ]
