# Generated by Django 6.0.3 on 2026-09-13 21:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0094_event_is_partiful_import"),
    ]

    operations = [
        migrations.AddField(
            model_name="surveyresponse",
            name="anonymous_token",
            field=models.CharField(blank=True, db_index=True, max_length=64, null=True),
        ),
    ]
