# Generated by Django 6.0.3 on 2026-10-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0095_event_is_legacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventrsvp",
            name="waitlist_position",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
