# Generated by Django 6.0.3 on 2026-09-13 21:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("community", "0095_event_is_legacy"),
    ]

    operations = [
        migrations.AddField(
            model_name="survey",
            name="closes_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="max_responses",
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="survey",
            name="opens_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
