# Generated by Django 5.2.12 on 2026-03-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_phone_number_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="needs_onboarding",
            field=models.BooleanField(default=False),
        ),
    ]
