# Generated by Django 5.2.12 on 2026-03-31 14:18

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_rename_manage_guidelines"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="show_email",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="user",
            name="show_phone",
            field=models.BooleanField(default=True),
        ),
    ]
