# Generated by Django 6.0.3 on 2026-04-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0015_user_login_link_requested"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="week_start",
            field=models.CharField(
                choices=[("sunday", "Sunday"), ("monday", "Monday")],
                default="sunday",
                max_length=10,
            ),
        ),
    ]
