# Generated by Django 6.0.3 on 2026-05-29 02:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0024_user_email_unique"),
    ]

    operations = [
        migrations.AddField(
            model_name="magiclogintoken",
            name="requires_password_reset",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="user",
            name="needs_password_reset",
            field=models.BooleanField(default=False),
        ),
    ]
