# Generated by Django 6.0.3 on 2026-06-04 21:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0025_magiclogintoken_requires_password_reset_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="guidelines_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
