# Generated by Django 6.0.3 on 2026-06-05 11:55

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0026_user_guidelines_consent_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="sms_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
