# Generated by Django 6.0.3 on 2026-06-24 10:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("users", "0027_user_sms_consent_at"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={},
        ),
        # Add with default=True so every existing row backfills to member, then
        # flip the field default to False so new (public-RSVP) accounts are
        # non-members unless a creation path explicitly opts them in.
        migrations.AddField(
            model_name="user",
            name="is_member",
            field=models.BooleanField(db_index=True, default=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="is_member",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddConstraint(
            model_name="user",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("email__isnull", False), models.Q(("email", ""), _negated=True)
                ),
                fields=("email",),
                name="unique_non_blank_email",
            ),
        ),
    ]
