# Generated by Django 6.0.3 on 2026-06-26 01:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0029_nonmemberrsvptoken"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo_updated_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
