# Generated by Django 6.0.3 on 2026-07-11 04:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0030_user_photo_updated_at"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="pronouns",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
