# Generated by Django 6.0.3 on 2026-07-11 16:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0031_user_pronouns"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="first_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
        migrations.AddField(
            model_name="user",
            name="last_name",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
