# Generated by Django 6.0.3 on 2026-07-12 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0033_backfill_user_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="hide_last_name",
            field=models.BooleanField(default=False),
        ),
    ]
