# Generated by Django 6.0.3 on 2026-07-12 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0033_backfill_user_names"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="nickname",
            field=models.CharField(blank=True, default="", max_length=64),
        ),
    ]
