# Generated by Django 6.0.3 on 2026-07-13 00:48

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0035_user_hide_last_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="display_name",
        ),
    ]
