# Generated by Django 6.0.3 on 2026-07-13 09:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0036_remove_user_display_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="magiclogintoken",
            name="source",
            field=models.CharField(
                choices=[("self_service", "Self-service"), ("admin", "Admin")],
                default="admin",
                max_length=20,
            ),
        ),
    ]
