# Generated by Django 6.0.3 on 2026-07-13 03:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0037_magiclogintoken_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="birthday",
            field=models.DateField(blank=True, null=True),
        ),
    ]
