# Generated by Django 6.0.3 on 2026-07-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0038_user_birthday'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='show_birthday',
            field=models.BooleanField(default=True),
        ),
    ]
