# Generated by Django 6.0.3 on 2026-07-18 17:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0040_birthday_month_day_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="contact_privacy_consent_at",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
