# Generated by Django 6.0.3 on 2026-08-01 00:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0042_normalize_phone_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="calendar_feed_excluded_types",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
