# Generated by Django 6.0.3 on 2026-08-10 03:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0042_normalize_phone_numbers"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="weekly_digest_opt_out",
            field=models.BooleanField(default=False),
        ),
    ]
