# Generated by Django 6.0.3 on 2026-09-13 19:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0044_user_calendar_feed_excluded_types"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="has_joined_whatsapp",
            field=models.BooleanField(default=False),
        ),
    ]
