# Generated by Django 6.0.3 on 2026-10-06 00:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0045_user_has_joined_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="session_version",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
