# Generated by Django 6.0.3 on 2026-09-13 22:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0045_user_has_joined_whatsapp"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="whatsapp_reminder_opt_out",
            field=models.BooleanField(default=False),
        ),
    ]
