# Generated by Django 6.0.3 on 2026-08-03 00:16

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="AuditLogEntry",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4, editable=False, primary_key=True, serialize=False
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True)),
                ("action", models.CharField(db_index=True, max_length=64)),
                ("actor_label", models.CharField(max_length=255)),
                (
                    "target_type",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("doc_folder", "Doc folder"),
                            ("document", "Document"),
                            ("editable_page", "Editable page"),
                            ("event", "Event"),
                            ("event_poll", "Event poll"),
                            ("event_tag", "Event tag"),
                            ("faq", "FAQ"),
                            ("feature_flag", "Feature flag"),
                            ("guidelines", "Guidelines"),
                            ("homepage", "Homepage"),
                            ("join_form_question", "Join form question"),
                            ("join_request", "Join request"),
                            ("member_promotion_message", "Member promotion message"),
                            ("role", "Role"),
                            ("survey", "Survey"),
                            ("survey_question", "Survey question"),
                            ("tentative_approval_message", "Tentative approval message"),
                            ("user", "User"),
                            ("welcome_template", "Welcome template"),
                            ("whatsapp_link", "WhatsApp link"),
                        ],
                        db_index=True,
                        max_length=32,
                    ),
                ),
                ("target_id", models.CharField(blank=True, max_length=64)),
                ("details", models.JSONField(blank=True, default=dict)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                ("level", models.PositiveSmallIntegerField()),
                (
                    "actor",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="audit_entries",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name_plural": "audit log entries",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["target_type", "target_id"], name="audit_audit_target__8a9e7e_idx"
                    ),
                    models.Index(
                        fields=["actor", "-created_at"], name="audit_audit_actor_i_55fb6e_idx"
                    ),
                ],
            },
        ),
    ]
